<br /><br />

<?php

function getEvaluate($ev) {
    if ($ev == 'e') {
        echo "ممتاز";
    } else if ($ev == 'vg') {
        echo "جيد جدا";
    } else if ($ev == 'g') {
        echo "جيد ";
    } else if ($ev == 'w') {
        echo "ضعيف";
    }
}
?>

<div  style="padding: 25px;">
    <table class = "table" DIR="rtl">
        <thead>
            <tr >
                <td> <strong>
                        اسم ولي الامر  </strong>
                </td>
                <td> <strong>
                        تقييم السؤال الاول  </strong>
                </td>
                <td> <strong>
                        تقييم السؤال التانى  </strong>
                </td>
                <td> <strong>
                        تقييم السؤال الثالث  </strong>
                </td>
                <td> <strong>
                        المقترحات  </strong>
                </td>

            </tr>
        </thead>
        <?php
        $i = -1;
        foreach ($this->evaluate as $evaluates) {
            $i ++;
            if ($i % 2 == 0) {
                echo "<tr class='success'>";
            } elseif ($i % 2 == 1) {
                echo "<tr class='active' >";
            }
            ?>

                <td>
    <?= $evaluates['fname'] . " " . $evaluates['lname'] ?>
                </td>
                <td>
    <?php getEvaluate($evaluates['q1']) ?>
                </td>
                <td>
    <?php getEvaluate($evaluates['q2']) ?>
                </td>
                <td>
    <?php getEvaluate($evaluates['q3']) ?>
                </td>
                <td>
    <?= $evaluates['suggestion'] ?>
                </td>


            </tr>



            <?php
        }
        ?>

    </table>
</div>





