
<div style="margin: 20%">
    

    <div class="panel-body">
        <font size="5"> <a href="<?= $this->baseUrl() ?>/category/addcategory"  style="text-decoration: none" 
                           class="btn active btn-block btn-success btn-default" type="button"> اضف تصنيف</a> </font>
    </div>
    
    <div class="panel-body">
        <font size="5"> <a href="<?= $this->baseUrl() ?>/story"  style="text-decoration: none"
                           class="btn active btn-block btn-success btn-default" type="button"> اضف قصة</a> </font>
    </div>
    
    <div class="panel-body">
        <font size="5"> <a href="<?= $this->baseUrl() ?>/events/addevent"  style="text-decoration: none"
                           class="btn active btn-block btn-success btn-default" type="button"> اضف حدث</a> </font>
    </div>
    
</div>