<style>
    a:link,
    a:visited
    {
        color: #0398CA;
    }

    span#zf-name
    {
        color: #91BE3F;
    }

    div#welcome
    {
        color: #FFFFFF;
        background-image: url(http://framework.zend.com/images/bkg_header.jpg);
        width:  600px;
        height: 400px;
        border: 2px solid #444444;
        overflow: hidden;
        text-align: center;
    }

    div#more-information
    {
        background-image: url(http://framework.zend.com/images/bkg_body-bottom.gif);
        height: 100%;
    }
</style>
<div id="welcome">
    <h1>Welcome to the <span id="zf-name">Zend Framework!</span></h1>

    <h3>This is your project's main page</h3>

    <div id="more-information">
        <p><img src="http://framework.zend.com/images/PoweredBy_ZF_4LightBG.png" /></p>
        <p>
            Helpful Links: <br />
            <a href="http://framework.zend.com/">Zend Framework Website</a> |
            <a href="http://framework.zend.com/manual/en/">Zend Framework Manual</a>
        </p>
    </div>
</div>

<div style="width:100%;margin: 5%">
    <div style="width:40%;float: left">
        <img alt="" class="roundrect" style="width:100%;" src="<?= $this->baseUrl() ?>/images/mission.jpg" /> 
    </div>
    
    <div style="width:40%;float: left;margin: 2%" dir="rtl">
        <ul>
        <li>
         نحن مجموعة من الشباب نتطلع الي
 تطوير المجتمع ومقتنعون تماما بأن هذا        
لن يتم الا من خلال زرع              
 المفاهيم الصحيحة في الاطفال
 بعيدا عن الطرق التقليدية للتعليم
        </li>
        <li> 
            و بدأنا بالسلوكيات و تعريف الطفل بالاسعافات الاولية
        </li>
        </ul> 
    </div>
</div>

<div style="clear: both"></div>

<div style="width:100%;margin: 5%" dir="rtl">
    <div style="width:40%; float: left">
        <img alt="" class="roundrect" style="width:100%;" src="<?= $this->baseUrl() ?>/images/siteDesc.jpg" /> 
    </div>
    
    <div style="width:40%;float: left;margin: 2%">
        <ul>
        <li>
            ينقسم الموقع الي جزء لاولياء الامور
            و جزء خاص بالطفل
        </li>
        <li> 
            <font style="color: #356635"><u>
            <b>الجزء الخاص بالطفل</b>
            </u></font><br>
            يستطيع الطفل مشاهدة قصص توصل له معلومة مفيدة
            
            <font style="color: #356635"><u>
            <br><b>الجزء الخاص باولياء الامور</b>
            </u></font><br>
            يستطيعون متابعة كل القصص التي يشاهدها ابنائهم 
            و تقييم ما يقدمه الموقع و كذلك تقييم مدي تأثير الموقع في الطفل
               
        </li>
        </ul> 
    </div>