

<br><br><br><br>

<div class="carousel slide" id="carousel-765973" >
    <ol class="carousel-indicators">
        <li class="active" data-slide-to="0" data-target="#carousel-765973">
        </li>
        <li data-slide-to="1" data-target="#carousel-765973">
        </li>
        <li data-slide-to="2" data-target="#carousel-765973">
        </li>
    </ol>
    <div class="slider">
      <div class="slider-wrapper theme-default">
            <div id="slider" class="nivoSlider">
                <img alt="" src="<?= $this->baseUrl() ?>/images/story1_1/HomeBackground.jpg"/>
                <img alt="" src="<?= $this->baseUrl() ?>/images/story1_1/homeStory1.jpg" />
                <img alt="" src="<?= $this->baseUrl() ?>/images/3.png">
                <img alt="" src="<?= $this->baseUrl() ?>/images/4.jpg" />
                
            </div>
        </div>
   </div>
</div>
    
<br><br>


<div style="clear: both"></div>

